### ISSUE TITLE
where leetcode problem?

### ISSUE THREAD

**Issue by clonker** [Obudo/python-code-lib#1]

**Comment by Obudo** [comment]
The leetcode problems are low-hanging fruits and thus left as an exercise to the reader

**Comment by Obudo** [comment]
@clonker there ya go!

**Comment by clonker** [comment]
😍 😍😍

**Comment by clonker** [comment]
You can test your implementation against scipy.sparse.csgraph.connected_components :)

**Comment by Obudo** [comment]
Why would I waste ten minutes testing my code when I can spend several hours crying because it doesn't work during a contest

**Comment by clonker** [comment]
no idea man. personally i prefer crying
